### ISSUE TITLE
Is there a way to disable the prompt when kill Emacs?

### ISSUE THREAD

**Issue by re-mx** [skeeto/skewer-mode#88]
Hello, and sorry for my poor English.

When I use `skewer-mode`, I get this prompt when I quit Emacs:
```
Active processes exist; kill them and exit anyway? (y or n)
```
![2018-12-07 7 51 39](https://user-images.githubusercontent.com/26828933/49646445-00124c80-fa5a-11e8-82d1-ee4542c2040d.png)

Is there any way to make this prompt not appear? 

Thanks.

**Comment by skeeto** [comment]
This is a message from Emacs, not Skewer, so you'll have to configure 
Emacs to not show it. It's most likely talking about the web server 
socket being open (and listening) since sockets are treated as processes 
by Emacs. Note, however, if you used run-skewer or similar to launch a 
browser tab, there's a chance one of the running processes is your 
browser and you may end up closing your browser along with Emacs.

If you're using Emacs 26.1 or later, set confirm-kill-processes to nil. 
If you're using an earlier version of Emacs, it's a bit trickier since 
all the solutions are hacks that seem to depend on the operating system 
and version of Emacs:

https://stackoverflow.com/questions/2706527/make-emacs-stop-asking-active-processes-exist-kill-them-and-exit-anyway

**Comment by re-mx** [comment]
Thank you.
